### ISSUE TITLE
how to import in Android Studio

### ISSUE THREAD

**Issue by Dirkstaal** [redmi2/android_packages_apps_Music#1]
title says it all please help

**Comment by pirej** [comment]
I have never used Android Studio, sorry.

**Comment by Dirkstaal** [comment]
can you just export it from eclipse with the graddle build ? files

**Comment by Dirkstaal** [comment]
heres instructions  below

**Comment by Dirkstaal** [comment]
Export from Eclipse
1. Update your Eclipse ADT Plugin to 22.0 or higher, then go to File | Export.
2. Go to Android now then click on Generate Gradle build files , then it would generate gradle file for you.
3. Select your project you want to export.
4. Click on finish now.

**Comment by pirej** [comment]
I don't get it, WHY are you asking ME, i don't use "Android Studio" and "Eclipse" for anything.

**Comment by Dirkstaal** [comment]
so you ain't  a developer ?

**Comment by pirej** [comment]
If you say so, im not.
